; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:heltec_wifi_lora_32_v3]
platform = espressif32
board = heltec_wifi_lora_32_v3
framework = arduino
monitor_speed = 9600
upload_port = COM4
build_flags = 
	-D TEST_MODE=1
lib_deps = 
	adafruit/Adafruit SSD1306@^2.5.9
	adafruit/Adafruit GFX Library@^1.11.9
	jgromes/RadioLib@^7.3.0
	bblanchon/ArduinoJson@^6.21.3
	adafruit/Adafruit BusIO@^1.11.0
	xreef/EByte LoRa E220 library@^1.0.8
	throwtheswitch/Unity@^2.6.1

[env:production]
extends = env:heltec_wifi_lora_32_v3
build_flags = 
	-D DEBUG_MODE=0
	-D TEST_MODE=0

[env:debug]
extends = env:heltec_wifi_lora_32_v3
build_flags =
	-D DEBUG_MODE=1
	-D TEST_MODE=0

[env:unit-test]
extends = env:heltec_wifi_lora_32_v3
build_src_filter = +<setup.cpp> +<utils.cpp> +<CommandProcessor.cpp> -<main.cpp>
test_build_src = yes

[env:feature-disabled]
extends = env:production
build_flags = 
	-D DEBUG_MODE=0
	-D TEST_MODE=0
	-D USE_DISPLAY=0
	-D USE_LORA=0
	-D USE_LORA_EXT=0
	-D USE_SERIAL_2=0

[platformio]
lib_dir = lib
